# Zitieren {#zitieren}
Wenn wir wissenschaftlich arbeiten, dann erfinden wir das Rad in der Regel nicht neu, sondern stützen uns auf die Arbeit anderer Forscher\*innen; das gilt in den Einzelwissenschaften ebenso wie in der Philosophie. Wir stehen dabei -- wie es Isaac Newton einmal unter Rückgriff auf ein Gleichnis aus dem Hochmittelalter ausgedrückt hat -- auf den Schultern von Riesen: »If I have seen further it is by standing on the shoulders of Giants« [@turnbull_correspondence_1959, S. 416]. Ganz in diesem Sinne hat Carl Sagan einige hundert Jahre später treffend gesagt: »Science is a collaborative enterprise spanning the generations. When it permits us to see the far side of some new horizon, we remember those who prepared the way, seeing for them also« [@sagan_cosmos_1980, Flg. 5].

Wenn wir in einem Text auf die Arbeit anderer Wissenschaftler\*innen Bezug nehmen, dann machen wir das durch Zitate deutlich. Im Folgenden widmen wir uns deswegen dem Zitieren in wissenschaftlichen Arbeiten. Zunächst werfen wir einen Blick darauf, warum wir überhaupt zitieren (Abschnitt \@ref(zitierenwarum)), bevor wir uns genauer anschauen, worauf beim Zitieren zu achten ist (Abschnitt \@ref(zitierenworauf)). Anschließend werden zwei Möglichkeigten des Zitierens mit konkreten Beispielen vorgestellt (Abschnitt \@ref(zitierenwie)).


## Warum wir zitieren {#zitierenwarum}
In einer Studienarbeit zitieren wir nicht, weil es eben irgendwie zum wissenschaftlichen Arbeiten dazugehört und unsere Prüfer\*innen das nun einmal von uns erwarten. Vielmehr ist dieser Umgang mit Quellen ein integraler Bestandteil wissenschaftlicher Arbeit, den wir beim Verfassen von Studienarbeiten einüben. Das Zitieren dient einer Reihe ganz konkreter Zwecke:

 - Wissenschaft ist --  wie Carl Sagen es oben ausgedrückt hat -- ein gemeinsames Unterfangen. Dazu gehört, dass Wissenschaftler\*innen ihre Arbeit gegenseitig kritisch prüfen. Die eigene Arbeit für andere möglichst einfach nachvollziehbar und nachprüfbar zu machen hilft damit nicht nur den Leser\*innen beim Verständnis, sondern ist auch für diesen Prozess gegenseitiger Überprüfung -- und damit für den wissenschaftlichen Fortschritt selbst -- von Vorteil.
 - Durch die Auswahl, wen man wie in seiner Arbeit zitiert, setzt man sich in Beziehung zu anderen Wissenschaftler\*innen und Philosoph\*innen aus Vergangenheit und Gegenwart; man verortet sich dadurch, dass man die Arbeit anderer -- sei es kritisch oder affirmativ -- aufnimmt, also selbst im Netz der Wissenschaft und der Philosophie. Das ist -- insbesondere natürlich, wenn es affirmativ geschieht -- auch eine Würdigung der Arbeit anderer.
 - Durch Zitate macht man deutlich, welche Gedanken oder Informationen von anderen übernommen und welche selbst hervorgebracht worden sind. Dadurch wird deutlich, was man selbst geleistet hat.

Neben diesen -- vielleicht etwas idealisierten -- Punkten gibt es auch ganz pragmatische Aspekte, die oft mit dem gegenwärtigen wissenschaftlichen Publikationssystem zusammenhängen. Manchmal zitiert man bewusst eigene Arbeiten, die noch nicht publiziert sind, die sich aber auf dem Weg befinden (also zum Beispiel schon als Arbeitspapier vorliegen, gerade im Begutachtungsprozess sind oder schon angenommen aber noch nicht gedruckt wurden), um andere darauf aufmerksam zu machen. Oder man zitiert Autor\*innen, die zu einem ähnlichen Thema bereits publiziert haben, weil sie potentielle Begutachter\*innen sein könnten und man sich einen Vorteil davon erhofft, wenn sie ihre eigene Arbeit in einem Manuskript wiederfinden (beziehungsweise einen Nachteil befürchtet, wenn sie das nicht tun). Oder man möchte zeigen, dass man gut in das Profil einer Zeitschrift passt, bei der man sein Manuskript einreicht [vgl. @baird_citations_1994].

Außerdem sanktioniert es die wissenschaftliche Gemeinschaft, wenn man beim Zitieren nachlässig ist. Macht man die Übernahme fremder Inhalte nicht hinreichend deutlich, spricht man von einem Plagiat. Jenachdem, wie schwerwiegend ein Plagiat ist, kann es zu einer Reihe unangenehmer Konsequenzen führen, bis hin zur Exmatrikulation oder der Aberkennung eines vormals erworbenen Titels. Die Pflicht zum richtigen Zitieren ist dabei nicht nur eine Übereinkunft innerhalb der wissenschaftlichen Gemeinschaft, sondern ist sogar juristisch geregelt; in Deutschland beispielsweise durch das _Gesetz über Urheberrecht und verwandte Schutzrechte_ (UrhG), dort insbesondere in § 51 (»Zitate«) und § 63 (»Quellenangabe«).


## Worauf wir beim Zitieren achten müssen {#zitierenworauf}
Es gibt eine Reihe von Punkten, die beim Zitieren wichtig sind. Allgemeinwissen oder Grundlagenwissen aus dem eigenen Fach müssen beispielsweise in der Regel nicht belegt werden. Als Daumenregel kann man sich hier an Norbert Franck orientieren, bei dem es heißt: »Zitate sollten nicht peinlich sein« [@franck_handbuch_2004, S. 296]; dass die Erde keine Scheibe ist oder dass Kant aus Königsberg stammt, gilt als hinreichend bekannt und gesichert, um ohne Quelle erwähnt werden zu können.

Ferner unterscheiden wir zwischen zitierfähigen und nicht zitierfähigen Quellen. Dabei kann die Verwendbarkeit einer Quelle auch vom Kontext abhängen. Soll die Quelle beispielsweise eine wissenschaftliche oder philosophische Aussage belegen, würde sich ein Artikel aus der BILD-Zeitung kaum eignen. Beschäftigt sich eine Arbeit aber beispielsweise mit der publizistischen Praxis der BILD-Zeitung, kann ein Artikel aus der Bild-Zeitung eine illustrative Funktion erfüllen und damit ihren berechtigten Platz in einer Arbeit haben. In jedem Fall aber soll die Quelle »vom Leser nachvollzogen und überprüft werden« können [@lueck_technik_2009, S. 67], sie soll also ihrer Funktion im Text _angemessen_ und auf die ein oder andere Weise _zugänglich_ sein.^[Dementsprechend schränken @rossig_wissenschaftliche_2005[S. 122] ein: »Von Dritten kaum zu beschaffende Quellen wie mündliche Auskünfte, nicht veröffentlichte Hausarbeiten, Studienarbeiten und Diplomarbeiten oder Vorlesungs-Skripte sind damit nicht oder nur in Sonderfällen zitierfähig.« Ähnlich auch @lueck_technik_2009[S. 67]: »Informationen aus Gesprächen oder Diskussionen sind nicht zitierfähig, da sie nicht nachvollzogen werden können.« Auf der anderen Seite gilt: »Zitierfähig ist grundsätzlich nur das, was vom Leser nachvollzogen und überprüft werden kann: Worte, Teilsätze (Passagen) und Sätze aus wissenschaftlich anerkannter Literatur, aber auch Gesetzestexte, Verordnungen, Richtlinien, Kommentare, veröffentlichte Statistiken, Berichte von Verbänden, Banken.« (ebd.)]

Liegt eine geeignete Quelle vor, gibt es verschiedene Möglichkeiten, aus ihr zu zitieren oder auf sie zu verweisen. Im Wesentlichen unterscheiden wir zwischen einem direkten (wörtlichen) Zitat (Abschnitt \@ref(zitierendirekt)), einem indirekten Zitat (Abschnitt \@ref(zitierenindirekt)) und einem bloßen Verweis (Abschnitt \@ref(zitierenverweis)).


### Das direkte Zitat {#zitierendirekt}
Wenn man den Wortlaut einer Quelle besonders treffend findet oder wenn er für die eigene Arbeit wichtig ist, kann man ihn wörtlich zitieren, wobei man mit solchen direkten Zitiaten eher sparsam umgehen sollte. Das wörtliche Zitat hat in einem inhaltlichen Zusammenhang zu dem voran- oder nachgehenden Text zu stehen, wird durch die Verwendung von Anführungszeichen kenntlich und durch eine Quellenangabe nachvollziehbar gemacht. Das kann dann beispielsweise so aussehen:

> Odo Marquard stellt sich selbst in die Tradition der Skepsis. In seiner Dankesrede zum Erhalt des Sigmund-Freud-Preises heißt es entsprechend: »Ich revanchiere mich -- Revance heißt Rache -- hier durch einige Bemerkungen über die Skeptiker, zu denen ich gehöre, also dadurch, daß ich Farbe bekenne: Tarnfarbe« [@marquard_skeptiker_1987, S. 6].

Wörtliche Zitate werden buchstaben- und zeichengetreu wiedergegeben, das heißt, dass orthographische oder interpunktionsbezogene Eigenheiten -- auch Fehler -- beibehalten werden. Möchte man darauf hinweisen, dass eine solche Eigenheit aus dem Original stammt und sich nicht durch falsches Zitieren eingeschlichten hat, kann man hinter der betreffenden Stelle den Hinweis »sic« (»sic erat scriptum«, »so stand es geschrieben«) anbringen. Das kann dann beispielsweise so aussehen:

> »Das aber wäre -- umkompensiert [sic] -- ein menschlich unaushaltbarer Verlust, weil zunehmend der lebensweltliche Bedarf der Menschen nicht mehr gedeckt wäre, in einer farbigen, vertrauten und sinnvollen Welt zu leben« [@marquard_unvermeidlichkeit_1987, S. 104].
<!-- »Es ist also -- als Freiheitswirkung -- zuträglich für den Menschen, viele ( mehrere) [sic] Überzeugungen zu haben« [@marquard_apologie_1987, S. 133] -->

Von dieser Pflicht zur zeichengetreuen Wiedergabe gibt es eine Ausnahme: Wenn im Zitat selbst Anführungszeichen enthalten sind, werden diese an den eigenen Stil angepasst, man mischt also nicht verschiedene typographische Arten von Anführungszeichen. Steht das Zitat in Anführungszeichen, wandelt man die im Zitat selbst enthaltenen Anführungszeichen außerdem in halbe Anführungszeichen um. Das kann dann beispielsweise so aussehen:

> Marquard rekurriert hier auf Plotin: »Ich meine, beim Rahmenthema ›Sinn im Horizont der Wissenschaft‹ kommt man als Philosoph ganz gut durch mit dieser -- Sie haben das sofort bemerkt -- Variante einer Formulierung von Wilhelm Busch, die da lautet: ›Das Gute, dieser Satz steht fest, ist stets das Böse, das man läßt‹« [@marquard_diaetetik_1987, S. 33].

Überschreitet ein wörtliches Zitat eine gewisse Länge -- oft spricht man von drei Zeilen --, setzt man es als sogenanntes Blockzitat vom übrigen Text ab. Es steht dann als eigener Absatz für sich. In der Regel wird dieser Absatz am linken -- manchmal auch am rechten -- Rand eingerückt. Oft ist auch die Schrift kleiner als im regulären Text. Bei solchen Zitaten können die Anführungszeichen an Anfang und Ende wegfallen. Sollten im Zitat selbst Anführungszeichen enthalten sein, müssen diese dann nicht in halbe Anführungszeichen umgewandelt werden.

Finden sich an einer Stelle, die man wörtlich zitiert, Hervorhebungen, beispielsweise durch Fettdruck, Kursivierung, Kapitälchen oder Unterstreichung, werden diese in der Regel auch übernommen, können aber an den eigenen Stil angepasst werden. Oft findet man an solchen Stellen einen Hinweis wie »Hervorh. i.O.« (»Hervorhebung im Original«). Das kann dann beispielsweise so aussehen:

> Als vierte Forderung führt Marquard an: »Man muß -- gerade auch gegenwärtig -- ablassen vom _Unsinn der Bindung der Lebensbejahung an den absoluten Sinnbeweis_« [@marquard_diaetetik_1987, S. 52, Hervorh. i.O.].

Es kann auch vorkommen, das man selbst etwas innerhalb eines Zitats hervorheben möchte. In diesem Fall bringt man einen ähnlichen Hinweis an, oft unter Verwendung der eigenen Initialen. Das kann dann beispielsweise so aussehen:

> Wobei Marquard auf drastische Formulierungen zurückgreift, etwas wenn er schreibt: »Sie antworten auf das _Trauma_ des hermeneutischen _Bürgerkriegs_« [@marquard_unvermeidlichkeit_1987, S. 109, Hervorh. A.M.B.].

Möchte man in einem wörtlichen Zitat Auslassungen, Anpassungen oder Anmerkungen vornehmen, lässt sich das durch die Verwendung eckiger Klammern kenntlich machen. Eine Auslassung kann dann beispielsweise so aussehen:

> »Die klassische Definition der Universalgeschichte [...] hat genau das, meine ich, übersehen« [@marquard_universalgeschichte_1987, S. 70].

Anpassung und Anmerkung können beispielsweise so aussehen:

> Marquard spricht von einer »wissenschaftlich betriebene[n] Form der Polymythie [dem Gegenteil der Monomythie]« [@marquard_universalgeschichte_1987, S. 71].


### Das indirekte Zitat {#zitierenindirekt}
Bei einem indirekten Zitat gibt man etwas _paraphrasiert_ wieder. Während sich ein direktes Zitat -- wovon natürlich tunlichst abzuraten ist -- auch setzen lässt, ohne dessen Inhalt vollständig verstanden zu haben, setzt eine gelungene Paraphrase voraus, dass man den Inhalt hinreichend gut durchdrungen hat, um ihn adäquat in eigene Worte übersetzen zu können. Ähnlich wie bei einem direkten Zitat weist man auch bei einem indirekten Zitat darauf hin, wo in einem Text sich die fragliche Stelle befindet. Anders als beim direkten Zitat weist bei einem indirekten Zitat oft das Kürzel »vgl.« (»vergleiche«) auf die sinngemäße Übernahme hin. Das kann dann zum Beispiel so aussehen:

> Dem Menschen in der modernen Gesellschaft attestiert Marquard einen Hang dazu, Fortschritten, die ihm von etwas Negativem entlasten, anschließend selbst Negativität zuzuschreiben [vgl. @marquard_zeitalter_1987, S. 87--92].


### Der Verweis {#zitierenverweis}
Nicht immer bezieht man sich auf eine spezifische Stelle in einem Text. Wenn man auf einen Text im Ganzen hinweisen möchte, lässt sich das durch einen Verweis machen. Das kann dann zum Beispiel so aussehen:

> Zur Rolle des Zufälligen für das menschliche Leben siehe @marquard_apologie_1987.


### Weitere Besonderheiten {#zitierenweiteres}
Es gibt einige Feinheiten, auf die wir beim Zitieren außerdem zu achten haben.


## Wie wir zitieren {#zitierenwie}
Es gibt eine ganze Reihe unterschiedlicher Zitierweisen, von denen hier exemplarisch nur ein prominenter Vertreter vorgestellt werden soll. Grob lässt sich unterscheiden zwischen solchen, die in Klammern zitieren, und solchen, die in Fuß- oder Endnoten zitieren. Das [Chicago Manual of Style](https://www.chicagomanualofstyle.org/home.html) (CMOS) bietet Vorgaben für beide Varianten an.

Die [Modern Language Association](https://www.mla.org/MLA-Style) oder die [American Psychology Association](https://apastyle.apa.org/) fokussieren sich auf das Zitieren in Klammern. Werfen wir im Folgenden der Reihe nach einen genaueren Blick auf diese Auswahl.


Seit 1906 erscheint bei der University of Chicago Press das _Chicago Manual of Style_ (CMOS), ein umfangreicher Styleguide für Amerikanisches Englisch, dessen 17. Auflage im Jahr 2017 erschienen ist.^[Vgl. The University of Chicago Press Editorial Staff (2017): _The Chicago Manual of Style. The Essential Guide for Writers, Editors, and Publishers_. 17. Auflage. Chicago und London: The University of Chicago Press.] Das Buch gliedert sich in drei Teile. Während sich der erste Teil verschiedenen Aspekten des Publikationsprozesses widmet, beleuchtet der zweite Teil unter anderem sprachliche und stilistische Aspekte. Der dritte Teil schließlich nimmt das Zitieren in den Blick. Wie oben angemerkt, liefert das CMOS sowohl Vorgaben für das Zitieren mit Fuß- oder Endnoten wie auch für das Zitieren mit Klammern. Im nächsten Abschnitt schauen wir uns zunächst die Variante mit Fuß- oder Endnoten an, im darauffolgenden Abschnitt dann die Variante mit Klammern.


### Zitieren mit Fuß- oder Endnoten
Beim Zitieren mit Fuß- oder Endnoten wird an derjenigen Stelle im Text, an der man auf eine Quelle verweisen möchte, eine hochgestellte Zahl gesetzt. Am Ende der Seite (im Fall von Fußnoten) oder am Ende des Textes (im Fall von Endnoten) taucht diese Zahl dann wieder auf, gefolgt von der Quellenangabe. Im Folgenden beschränken wir uns bei Erklärungen und Beispielen der Einfachheit halber auf Fußnoten; der Unterschied zu Endnoten besteht praktisch nur darin, wo die Quellenangaben plaziert werden, also am Seiten- oder am Textende.

Wird eine Quelle das erste Mal in einem Text genannt, beinhaltet die Fußnote eine vollständige Quellenangabe. Wird an späterer Stelle im Text erneut auf diese Quelle verwiesen, taucht in der entsprechenden Fußnote nur noch eine Kurzfassung der Quellenangabe auf. Die Fußnoten eines Textes sind fortlaufend nummeriert und starten mit einer 1. Am Ende des Textes listet ein Literaturverzeichnis die einzelnen Quellen auf.

Nachfolgend geben wir für die gängigen Arten von Quellen an, wie eine vollständige Quellenangabe, deren Kurzfassung sowie der entsprechende Eintrag im Literaturverzeichnis -- leicht angepasst für den deutschen Sprachraum^[Diese Anpassung betreffen Übersetzung (»Nr.« statt »No.«, ) sowie Interpunktion (Interpunktionszeichen außerhalb statt innerhalb von Anführungen, Wegfall des Oxford-Kommas).] -- nach dem CMOS aussehen kann.^[Vgl. The University of Chicago Press Editorial Staff, _The Chicago Manual of Style_. Kap. 14.]


##### Monographie
Vollständige Quellenangabe:

> 1. Alex Reinhart, _Statistics Done Wrong: Statistik richtig anwenden und gängige Fehler vermeiden_ (Frechen: mitp, 2016), 29.
> 2. Justin Sytsma und Jonathan Livengood, _The Theory and Practice of Experimental Philosophy_ (Peterborough: Broadview, 2016), 150--58.

Gekürzte Quellenangabe:

> 3. Reinhart, _Statistics Done Wrong_, 87.
> 4. Sytsma und Livengood, _The Theory and Practice of Experimental Philosophy_, 169.

Literaturverzeichnis:

> Reinhart, Alex. _Statistics Done Wrong: Statistik richtig anwenden und gängige Fehler vermeiden_. Frechen: mitp, 2016.
>
> Sytsma, Justin, und Jonathan Livengood. _The Theory and Practice of Experimental Philosophy_. Peterborough: Broadview, 2016.


##### Sammelband oder andere Herausgabe
Vollständige Quellenangabe:

> 1. Stefan Traub und Bernhard Kittel, Hrsg., _Need-Based Distributive Justice: An Interdisciplinary Perspective_ (Cham: Springer, 2020).

Gekürzte Quellenangabe:

> 2. Traub und Kittel, _Need-Based Distributive Justice_.

Literaturverzeichnis:

> Traub, Stefan, und Bernhard Kittel, Hrsg. _Need-Based Distributive Justice: An Interdisciplinary Perspective_. Cham: Springer, 2020.


#### Beitrag in einem Sammelband
Bei Beiträgen aus Sammelbänden werden Seitenzahlen nur dann in Fußnoten aufgenommen, wenn Sie auf eine spezifische Stelle hinweisen (Beispiel 1). Die Seitenspanne, also von welcher bis zu welcher Seite ein Beitrag in einem Sammelband reicht, wird im Literaturverzeichnis genannt.

Vollständige Quellenangabe:

> 1. Mark Siebel und Thomas Schramme, »Need-Based Justice from the Perspective of Philosophy«, in _Need-Based Distributive Justice: An Interdisciplinary Perspective:, hrsg. Stefan Traub und Bernhard Kittel (Cham: Springer, 2020), 24.

Gekürzte Quellenangabe:

> 2. Siebel und Schramme, »Need-Based Justice«.

Literaturverzeichnis:

> Siebel, Mark, und Thomas Schramme. »Need-Based Justice from the Perspective of Philosophy«. In _Need-Based Distributive Justice: An Interdisciplinary Perspective:, herausgegeben von Stefan Traub and Bernhard Kittel, 21--58. Cham: Springer, 2020.


##### Übersetztes Buch
Es wird immer mal wieder vorkommen, dass wir auf ein Buch stoßen, dessen Originalsprache wir nicht beherrschen. In diesem Fall kommen wir nicht um Übersetzungen herum, wenn das Buch für unsere Arbeit relevant ist und die Zeit für ein umfassendes Fremdsprachenstudium fehlt. Aber auch, wenn wir das Original zu lesen im Stande sind, kann der Blick in eine Übersetzung spannend oder hilfreich sein. Zitiert man solch eine übersetzte Fassung, dann gibt man auch an, wer die Übersetzung besorgt hat.

Vollständige Quellenangabe:

> 1. David Miller, _Grundsätze sozialer Gerechtigkeit_, übers. Ulrike Berger (Frankfurt: Campus, 2008).

Gekürzte Quellenangabe:

> 2. Miller, _Grundsätze sozialer Gerechtigkeit_.

Literaturverzeichnis:

> Miller, David. _Grundsätze sozialer Gerechtigkeit_. Übersetzt von Ulrike Berger. Frankfurt: Campus, 2008.


##### Artikel in einer Fachzeitschrift
Bei Artikeln aus Fachzeitschriften, den im Forschungsalltag wahrscheinlich wichtigsten und am häufigsten genutzten Quellen, sieht das CMOS vor, dass Seitenzahlen in Fußnoten nur aufgenommen werden, wenn Sie auf eine spezifische Stelle hinweisen, etwa im Zuge eines Zitats (Beispiel 1). Die Seitenspanne, also von welcher bis zu welcher Seite ein Artikel in einer Fachzeitschrift reicht, wird nur im Literaturverzeichnis genannt. Bei Artikeln, die online abgerufen wurden, sieht das CMOS vor, URL oder DOI anzugeben (Beispiel 2), wobei DOI der URL vorzuziehen ist.

Hat ein Artikel vier bis zehn Autor\*innen, wird in der Fußnote nur die erste Person genannt (Beispiel 3), während im Literaturverzeichnis auch die restlichen aufgeführt werden. Wenn ein Artikel elf oder mehr Autor\*innen hat, wird genauso verfahren, aber im Literaturverzeichnis werden nur die ersten sieben namentlich erwähnt (Beispiel 4).

Vollständige Quellenangabe:

> 1. Joshua Knobe, »Intentional Action and Side Effects in Ordinary Language«, _Analysis_ 63, Nr. 3 (Juli 2003): 192.
> 2. Jonathan Livengood und Justin Sytsma, »Actual Causation and Compositionality«, _Philosophy of Science_ 87, Nr. 1 (Januar 2020), https://doi.org/10.1086/706085.
> 3. Luke Buckland et al., »Testing the Motivational Strength of Positive and Negative Duty Arguments Regarding Global Poverty”, _Review of Philosophy and Psychology_ 13, Nr. 3 (Mai 2021): 707, https://doi.org/10.1007/s13164-021-00555-4.
> 4. Florian Cova et al., »Estimating the Reproducibility of Experimental Philosophy”, _Review of Philosophy and Psychology_ 12, Nr. 1 (März 2021), https://doi.org/10.1007/s13164-018-0400-9.

Gekürzte Quellenangabe:

> 5. Joshua Knobe, »Intentional Action«.
> 6. Livengood und Sytsma, »Actual Causation«.
> 7. Buckland et al., »Testing the Motivational Strength«.
> 8. Cova et al., »Estimating the Reproducibility«.

Literaturverzeichnis:

> Buckland, Luke, Matthew Lindauer, David Rodríguez-Arias und Carissa Véliz. »Testing the Motivational Strength of Positive and Negative Duty Arguments Regarding Global Poverty”. _Review of Philosophy and Psychology_ 13, Nr. 3 (Mai 2021): 463--73. https://doi.org/10.1007/s13164-021-00555-4.
>
> Cova, Florian, Brent Strickland, Angela Abatista, Aurélien Allard, James Andow, Mario Attie, James Beebe et al. »Estimating the Reproducibility of Experimental Philosophy”. _Review of Philosophy and Psychology_ 12, Nr. 1 (März 2021): 9--44. https://doi.org/10.1007/s13164-018-0400-9.
>
> Knobe, Joshua. »Intentional Action and Side Effects in Ordinary Language«. _Analysis_ 63, Nr. 3 (Juli 2003): 190--94.
>
> Livengood, Jonathan, und Justin Sytsma. »Actual Causation and Compositionality«. _Philosophy of Science_ 87, Nr. 1 (Januar 2020): 43--69. https://doi.org/10.1086/706085.


##### Artikel in einer populären Zeitung oder Zeitschrift
Bei Artikeln aus Zeitungen und Zeitschriften können die Seitenzahlen in der Fußnote genannt werden, fallen aber bei der Angabe im Literaturverzeichnis fort (Beispiel 1). Bezieht man sich auf die Online-Fassung eines Artikels, wird die URL mit angegeben (Beispiel 2).

Vollständige Quellenangabe:

> 1. Christian Endt, Nico Fried und Kristiana Ludwig, »Der lange Weg zur Normalität«, _Süddeutsche Zeitung_, 6. April 2020, 2. <!-- Ausgabe 81/2020 -->
> 2. Björn Stephan, »Wer ist eigentlich meine verrückte Nachbarin?«, _Zeit Online_, 16. Februar 2017, https://www.zeit.de/2017/08/hamburg-st-pauli-eva-nachbarin-barbara-bar.

Gekürzte Quellenangabe:

> 3. Endt, Fried und Ludwig, »Der lange Weg zur Normalität«.
> 4. Stephan, »Wer ist eigentlich meine verrückte Nachbarin?«.

Literaturverzeichnis:

> Endt, Christian, Nico Fried und Kristiana Ludwig. »Der lange Weg zur Normalität«. _Süddeutsche Zeitung_, 6. April 2020.
>
> Stephan, Björn. »Wer ist eigentlich meine verrückte Nachbarin?«. _Zeit Online_, 16. Februar 2017, https://www.zeit.de/2017/08/hamburg-st-pauli-eva-nachbarin-barbara-bar.


##### Buchbesprechung
Neu erschienene Bücher werden immer wieder auch in populären Medien, etwa in überregionalen Zeitungen, besprochen. Solche Rezensionen lassen sich wie folgt zitieren.

Vollständige Quellenangabe:

> 1. Franz Schuh, »Zerstört Bankkonten! Christian Neuhäuser philosophiert über Reichtum«. Rezension zu _Wie reich darf man sein?_ von Christian Neuhäuser, _Die Zeit_, 22. August 2019. <!-- Ausgabe 35/2019, S. 38, https://www.zeit.de/2019/35/wie-reich-darf-man-sein-christian-neuhaeuser-reichtum -->

Gekürzte Quellenangabe:

> 2. Schuh, »Zerstört Bankkonten!«.

Literaturverzeichnis:

> Schuh, Franz. »Zerstört Bankkonten! Christian Neuhäuser philosophiert über Reichtum«. Rezension zu _Wie reich darf man sein?_ von Christian Neuhäuser. _Die Zeit_, 22. August 2019. <!-- Ausgabe 35/2019, S. 38, https://www.zeit.de/2019/35/wie-reich-darf-man-sein-christian-neuhaeuser-reichtum -->


##### Interview
Interviews, etwa im Rahmen einer Radiosendung oder eines Podcasts, können wie folgt zitiert werden.

Vollständige Quellenangabe:

> 1. Marina Schubarth, »Molotowcocktails statt Proben«, Interview von Susanne Burkhardt, _Rang 1_, Deutschlandfunk Kultur, 5. März 2022, Audio, 3:40, https://www.deutschlandfunkkultur.de/ukrainische-theatermacher-im-krieg-100.html.

Gekürzte Quellenangabe:

> 2. Schubarth, Interview.

Literaturverzeichnis:

> Schubarth, Marina. »Molotowcocktails statt Proben«. Interview von Susanne Burkhardt. _Rang 1_, Deutschlandfunk Kultur, 5. März 2022. Audio, 3:40. https://www.deutschlandfunkkultur.de/ukrainische-theatermacher-im-krieg-100.html.


##### Dissertation oder Abschlussarbeit
Dissertationen oder Abschlussarbeiten werden von der Hochschule, an der sie verfasst worden sind, archiviert. Wenn sie außerdem als Monographie bei einem Verlag publiziert werden, lässt sich diese verlegte Fassung zitieren. Liegt nur die von der Hochschule archivierte Fassung vor, sei es gedruckt oder online, kann wie folgt auf sie verwiesen werden.

Vollständige Quellenangabe:

> 1. Marc Wyszynski, »Der Einfluss von Framing, Medienpriming, Vorurteilen und Debiasing auf die Bewertung eines Betrugs an der Solidargemeinschaft« (Dissertation, Jacobs University Bremen, 2020). <!-- https://opus.constructor.university/frontdoor/index/index/docId/911 -->

Gekürzte Quellenangabe:

> 2. Wyszynski, »Der Einfluss von Framing«

Literaturverzeichnis:

> Wyszynski, Marc. »Der Einfluss von Framing, Medienpriming, Vorurteilen und Debiasing auf die Bewertung eines Betrugs an der Solidargemeinschaft«. Dissertation, Jacobs University Bremen, 2020.


##### Inhalte auf Websites
Möchte man an einer Stelle im Text auf eine Website verweisen, kann das wie folgt geschehen. Ist auf der Website angegeben, wann sie veröffentlicht oder das letzte Mal aktualisiert wurde, kann dieses Datum in die Quellenangabe übernommen werden (Beispiel 1), andernfalls wird das Abrufdatum genannt (Beispiel 2).

Vollständige Quellenangabe:

> 1. Masaharu Mizumoto, »A Prolegomenon to the Empirical Cross-Linguistic Study of Truth«, The New Experimental Philosophy Blog, veröffentlicht am 14. Oktober 2022, https://xphiblog.com/a-prolegomenon-to-the-empirical-cross-linguistic-study-of-truth/.
> 2. »Kennzahlen«, Google Scholar, abgerufen am 26. Juni 2023.
> 3. Andrew Hasse, »Being 97«, YouTube, veröffentlicht am 14. Januar 2020, Video, 18:12, https://youtu.be/qX6NztnPU-4.

Gekürzte Quellenangabe:

> 4. Mizumoto, »A Prolegomenon to the Empirical Cross-Linguistic Study of Truth«.
> 5. Google, »Kennzahlen«.
> 6. Hasse, »Being 97«.

Literaturverzeichnis:

> Google. »Kennzahlen«. Abgerufen am 26. Juni 2023. https://scholar.google.de/citations?view_op=metrics_intro.
>
> Hasse, Andrew. »Being 97«. YouTube. Veröffentlicht am 14. Januar 2020. Video, 18:12. https://youtu.be/qX6NztnPU-4.
>
> Mizumoto, Masaharu. »A Prolegomenon to the Empirical Cross-Linguistic Study of Truth«. The New Experimental Philosophy Blog. Veröffentlicht am 14. Oktober 2022. https://xphiblog.com/a-prolegomenon-to-the-empirical-cross-linguistic-study-of-truth/.


##### Inhalt in Sozialen Netzwerken
Wenn man -- etwa zur Illustration eines Punktes -- auf etwas verweisen möchte, das eine Person in einem Sozialen Netzwerk geäußert hat, gibt es im Regelfall keinen Titel, den man für die Quellenangabe heranziehen kann. Das CMOS schlägt vor, stattdessen die ersten bis zu 160 Zeichen des Beitrags zu verwenden. Eine Aufnahme in das Literaturverzeichnis folgt für gewöhnlich nicht.

Vollständige Quellenangabe:

> 1. Donald J. Trump (\@realDonaldTrump), »Sorry losers and haters, but my I.Q. is one of the highest«, Twitter, 9. Mai 2013, https://twitter.com/realDonaldTrump/status/332308211321425920.

Gekürzte Quellenangabe:

> 2. Trump, »Sorry losers and haters«.


##### Persönliche Korrespondenz
Beruft man sich an einer Stelle im Text auf die eigene Korrespondenz mit einer anderen Person, kann man darauf wie folgt in einer Fußnote hinweisen. In das Literaturverzeichnis wird so etwas in der Regel nicht aufgenommen.

Vollständige Quellenangabe:

> 1. Guillermina Jasso, E-Mail an den Autor, 23. Mai 2020.


##### Kommentar
Kommentare, zum Beispiel unter Videos auf YouTube (Beispiel 2), unter Beiträgen auf einem Blog oder unter Online-Artikeln einer Zeitung (Beispiel 4), Antworten auf Tweets (Beispiel 6) und ähnliches werden in Bezug auf die Kommentierte Quelle (Beispiele 1, 3 und 5) zitiert. Sie werden in aller Regel nicht in das Literaturverzeichnis aufgenommen.

Manchmal ist nicht auf den ersten Blick ersichtlich, wann ein Kommentar verfasst wurde. Bei YouTube lässt sich das noch rekonstruierten, wenn der Kommentar erst wenige Tage alt ist und neben dem Nutzernamen beispielsweise »vor 2 Tagen« angezeigt wird. Bei längeren Zeiträumen, wenn etwa nur noch »vor 2 Jahren« neben dem Nutzernamen steht, werden diese Angaben allerdings unscharf und eine Rekonstruktion ist nicht mehr durch einfaches Rückrechnen möglich. Die genauen Daten liegen im Hintergrund aber nichtsdestotrotz vor und es gibt Möglichkeiten, sie sichtbar zu machen.^[Für Kommentare bei YouTube ermöglicht das zum Beispiel die Website https://hadzy.com/.]

Vollständige Quellenangabe:

> 1. Andrew Hasse, »Being 97«, YouTube, veröffentlicht am 14. Januar 2020, Video, 18:12, https://youtu.be/qX6NztnPU-4.
> 2. Bill Farley (\@billfarley9167), 27. Januar 2021, 4:04 Uhr, Kommentar zu Hasse, »Being 97«.
> 3. Masaharu Mizumoto, »A Prolegomenon to the Empirical Cross-Linguistic Study of Truth«, The New Experimental Philosophy Blog, veröffentlicht am 14. Oktober 2022, https://xphiblog.com/a-prolegomenon-to-the-empirical-cross-linguistic-study-of-truth/.
> 4. Izabela Skoczeń, 14. Oktober 2022, 21:07 Uhr, Kommentar zu Mizumoto, »A Prolegomenon to the Empirical Cross-Linguistic Study of Truth«.
> 5. Donald J. Trump (\@realDonaldTrump), »Sorry losers and haters, but my I.Q. is one of the highest«, Twitter, 9. Mai 2013, https://twitter.com/realDonaldTrump/status/332308211321425920.
> 6. Joyce Carol Oates (\@JoyceCarolOates), 8. November 2016, 20:24 Uhr, Kommentar zu Trump, »Sorry losers and haters«.


#### Zitieren mit Klammern


##### Monographie
Quellenangabe:

> (Reinhart 2016, 29)
>
> (Sytsma und Livengood 2016, 150--58)

Literaturverzeichnis:

> Reinhart, Alex. _Statistics Done Wrong: Statistik richtig anwenden und gängige Fehler vermeiden_. Frechen: mitp, 2016.
>
> Sytsma, Justin, und Jonathan Livengood. _The Theory and Practice of Experimental Philosophy_. Peterborough: Broadview, 2016.


### Modern Language Association (MLA)


### American Psychology Association (APA)
