# Literaturempfehlungen {#literatur}

## Einführungen

### Allgemeine Einführungen
Es gibt eine ganze Reihe allgemeiner Einführungen, die einen erste Überblick über Geschichte und Themen der (westlichen) Philosophie bieten. Im Folgenden finden Sie eine kleine Auswahl solcher Einführungen.

- Anzenbacher, Arno (2010): *[Einführung in die Philosophie](https://www.herder.de/theologie-pastoral/shop/p2/29364-einfuehrung-in-die-philosophie-kartonierte-ausgabe/)*. 7. Auflage. Freiburg im Breisgau: Herder.
- Beckermann, Ansgar; Perler, Dominik (Hrsg.) (2010): *[Klassiker der Philosophie heute](https://www.reclam.de/detail/978-3-15-018731-9/Klassiker_der_Philosophie_heute/)*. 2., durchgesehene und erweiterte Auflage. Stuttgart: Reclam.
- Deleuze, Gilles; Guattari, Félix (2000): *[Was ist Philosophie?](https://www.suhrkamp.de/buch/was-ist-philosophieo-t-9783518290835/)*. Übersetzt von Bernd Schwibs und Joseph Vogl. 8. Auflage. Frankfurt am Main: Suhrkamp.
- Ferber, Rafael (2009): *[Philosophische Grundbegriffe. Eine Einführung. Bd. 1](https://www.chbeck.de/ferber-philosophische-grundbegriffe-1/product/27652/)*. 8., durchgesehene Auflage. München: C. H. Beck.
- Ferber, Rafael (2018): *[Philosophische Grundbegriffe. Eine Einführung. Bd. 2](https://www.chbeck.de/ferber-philosophische-grundbegriffe-1/product/27652/)*. 2. Auflage. München: C. H. Beck.
- Fischer, Eugen; Vossenkuhl, Wilhelm (Hrsg.) (2003): *[Die Fragen der Philosophie. Eine Einführung in Disziplinen und Epochen](https://www.chbeck.de/fischer-vossenkuhl-fragen-philosophie/product/13262/)*. München: C. H. Beck.
- Höffe, Otfried (2008): *[Klassiker der Philosophie. Bd. 1. Von den Vorsokratikern bis David Hume](https://www.chbeck.de/hoeffe-klassiker-philosophie-bd-1-vorsokratikern-david-hume/product/23211/)*. München: C. H. Beck.
- Höffe, Otfried (2008): *[Klassiker der Philosophie. Bd. 2. Von Immanuel Kant bis John Rawls](https://www.chbeck.de/hoeffe-klassiker-philosophie-bd-2-immanuel-kant-john-rawls/product/23212/)*. München: C. H. Beck.
- Kunzmann, Peter; Burkard, Franz-Peter; Wiedmann, Franz (2011): *[dtv-Atlas Philosophie](https://www.dtv.de/buch/dtv-atlas-philosophie-3229)*. 18. Auflage. München: dtv.
- Liessmann, Konrad Paul (2003): *[Die großen Philosophen und ihre Probleme. Vorlesungen zur Einführung in die Philosophie](https://www.utb.de/doi/book/10.36198/9783838522470)*. 4. Auflage. Wien: Facultas.
- Mall, Ram Adhar (2006): *[Philosophie im Vergleich der Kulturen. Interkulturelle Philosophie – eine neue Orientierung](https://www.wbg-wissenverbindet.de/shop/32300/philosophie-im-vergleich-der-kulturen/)*. Sonderausgabe der 1. Auflage 1995. Darmstadt: Wissenschaftliche Buchgesellschaft.
- Pfister, Jonas (2011): *[Philosophie. Ein Lehrbuch](https://www.reclam.de/detail/978-3-15-018767-8/Pfister__Jonas/Philosophie)*. 2., erweiterte Auflage. Stuttgart: Reclam.
- Salamun, Kurt (Hrsg.) (2009): *[Was ist Philosophie? Neuere Texte zu ihrem Selbstverständnis](https://www.utb.de/doi/book/10.36198/9783825210007)*. 5., erweiterte Auflage. Tübingen: Mohr Siebeck.

### Themenspezifische Einführungen

### Personenspezifische Einführungen

### Werkspezifische Einführungen

### Methodenspezifische Einführungen
- Büttemeyer, Wilhelm (2014): *[Logik zur Einführung](https://www.junius-verlag.de/Programm/Zur-Einfuehrung/Logik-zur-Einfuehrung.html)*. Hamburg: Junius.
- Damschen, Gregor; Schönecker, Dieter (2013): *[Selbst philosophieren. Ein Methodenbuch](https://www.degruyter.com/document/doi/10.1515/9783110265194/)*. 2., durchgesehene und überarbeitete Auflage. Berlin und Boston: de Gruyter.
- Flatscher, Matthias; Posselt, Gerald; Weiberg, Anja (2011): *[Wissenschaftliches Arbeiten im Philosophiestudium](https://www.utb.de/doi/book/10.36198/9783838550077)*. 2., aktualisierte Auflage. Wien: Facultas.
- Hübner, Dietmar (2013): *[Zehn Gebote für das philosophische Schreiben](https://www.utb.de/doi/book/10.36198/9783838540184)*. 2. Auflage. Göttingen: Vandenhoek & Ruprecht.
- Kornmesser, Stephan; Bauer, Alexander Max; Alfano, Mark; Allard, Aurélien; Baumgartner, Lucien; Cova, Florian; Engelhardt, Paul; Fischer, Eugen; Meyer, Henrike; Reuter, Kevin; Sytsma, Justin; Thompson, Kyle; Wyszynski, Marc (in Vorbereitung): *Experimental Philosophy for Beginners. A Gentle Introduction to Methods and Tools*. Cham: Springer.
- Zoglauer, Thomas (2016): *[Einführung in die formale Logik für Philosophen](https://www.utb.de/doi/book/10.36198/9783838545929)*. 5., durchgesehene Auflage. Göttingen: Vandenhoeck & Ruprecht.

## Nachschlagewerke

## Periodika
Die aktuellen philosophischen Debatten finden zum wahrscheinlich größten Teil in wissenschaftlichen Fachzeitschriften statt. Wenn Sie wissen möchten, was derzeit diskutiert wird, lohnt sich also ein Blick in die ein oder andere Zeitschrift. Während es auch allgemeine Zeitschriften gibt, sind viele auf einen mehr oder weniger engen thematischen Rahmen spezialisiert. Im Folgenden finden Sie eine kleine Auswahl gängiger Periodika.

### Allgemeine Periodika

### Personenspezifische Periodika
